### ISSUE TITLE
Update launch files

### ISSUE THREAD

**Issue by A-make** [thentnucyborg/CyborgRobot#30]
- [ ] Launch ROS system upon robot boot

Boot flow: 
- Launch into IDLE state wait for commander node to send commands. 
- Controller nodes (audio, LED, navigation) go into boot cycle and then idle.
- Behaviour is at IDLE until commanded to start.

**Comment by JohanneLun** [comment]
a tiny script running `roslaunch cyborg.launch` called 'startup_cyborg.sh' has been created and tested on the robot (it works by running it in the terminal, but has not been tested at robot boot).
It can be found in /src/cyborg_launch/
