### ISSUE TITLE
Update setup.sh

### ISSUE THREAD

**Issue by A-make** [thentnucyborg/CyborgRobot#8]
#### setup.sh
- [x] update [setup.sh](https://github.com/thentnucyborg/CyborgRobot/blob/master/CyborgRobotInfo/pioneerlx_setup/setup.sh)
- [x] test that the script works
- [x] move script to setup/ folder
- [x] add README to setup/

#### requirements.txt
- [x] create requirements.txt for pip (see [requirements files](https://pip.pypa.io/en/stable/user_guide/#requirements-files)). This ensures that the correct version Python libraries are installed so that the system doesn't break due to library updates.
  - `pip freeze > requirements.txt` (remove libraries not used by the robot)
- [x] Add to setup.sh
  - `pip install -r requirements.txt`

**Comment by JohanneLun** [comment]
There may be some excess libraries in requirements.txt but many not used by the robot have been removed.
